class Style:
    WIDGETS_BG = '#FFA764'
    WIDGETS_FG_TEXT_COLOR = '#000000'
    WIDGETS_BORDER_COLOR = '#BF5200'
    WIDGETS_FONT = ("Comic Sans MS", 12)
    WINDOW_BG = '#FFE2CC'
    USER_BUBBLE_BG = WIDGETS_PROGRESS_BAR_COLOR = '#00FF22'
    ROBBY_BUBBLE_BG = '#4DB8EE'
    ERROR_BUBBLE_COLOR = "#E74B20"
    CONTEXT_BUBBLE_COLOR = "#E39CF7"

